### ISSUE TITLE
Unable to start when fish is the default shell

### ISSUE THREAD

**Issue by pedrocatalao** [MaccaTech/postgresql-mac-preferences#12]
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.

**Comment by mckenfra** [comment]
Thanks a lot for raising this. I am not familiar with fish. Could you suggest a fix? Here are some of the shell commands that the preferences runs:

    # Create plist file in temp dir
    echo {plist_xml} > {file_path} && chown {user} {file_path}
    
    # Move plist to system dir
    mv {temp_plist_path} {final_plist_path} && chown {user} {final_plist_path}
    
    # Start postgresql daemon
    launchctl load -F {plist_file} && sleep 1
    
    # Stop postgresql daemon
    launchctl remove {plist_file} && sleep 1

**Comment by pedrocatalao** [comment]
You're welcome.

I think the easiest way to do fix it is to force using bash like this:

``bash -c 'echo {plist_xml} > {file_path} && chown {user} {file_path}'``

**Comment by pedrocatalao** [comment]
Other possible solutions I can think of:
* allow editing the command lines
* being able to choose what shell to use
* auto detect default shell

**Comment by mckenfra** [comment]
I've released v2.4.2 containing a fix. Can you check if it now works?

Download the latest release at: https://github.com/mckenfra/postgresql-mac-preferences/releases

**Comment by pedrocatalao** [comment]
Thanks a lot, it didn't fix it for me though, I still get this:
<img width="780" alt="screen shot 2016-02-07 at 22 11 48" src="https://cloud.githubusercontent.com/assets/5308797/12875727/61bc7dda-cde8-11e5-8d0a-421ae5d350eb.png">
Maybe it's easier if you install fish (https://fishshell.com/) just to test it out, set it as default shell with ``chsh -s /usr/local/bin/fish`` and then go back to bash with ``chsh -s /bin/bash``

By the way, I made this set of server status icons for you, not sure if they fit well but if you think so, feel free to use them to replace the low resolution gear icon you're using: [server-status-images.zip](https://github.com/MaccaTech/postgresql-mac-preferences/files/120950/server-status-images.zip)

**Comment by mckenfra** [comment]
Ok thanks, I will try to install fish. As you say, it will make it easier to develop a fix and check that it works.

Your icons are absolutely fantastic, thank you so much! I'll put them in the app and see how they look. I'm worried they might almost be TOO cool... ;)

**Comment by mckenfra** [comment]
I tried your new icons in the app. Looks good, but I think they may be a little dark. See screenshot below - what do you think? Could you maybe send me one icon with the shadow removed, and maybe another one with the shadow removed and also a lighter colour for the metal?

<img width="780" alt="screen shot 2016-02-08 at 15 48 30" src="https://cloud.githubusercontent.com/assets/439593/12888668/86921c44-ce7b-11e5-8504-58166067d35a.png">

**Comment by pedrocatalao** [comment]
Here you go, I also included the photoshop file, change it as you please :)

[server-status-images2.zip](https://github.com/MaccaTech/postgresql-mac-preferences/files/121732/server-status-images2.zip)

**Comment by mckenfra** [comment]
I just uploaded a new build of v2.4.2, which contains the fish fix and the new server status icons. Let me know if it now works correctly for you.

Download the latest release at: https://github.com/mckenfra/postgresql-mac-preferences/releases

**Comment by pedrocatalao** [comment]
It works!! thanks for fixing it :) The only thing I noticed is that there is no starting/stopping image anymore, which kinda breaks the "animation"... I was expecting to see the yellow led for the starting and stopping states.

**Comment by mckenfra** [comment]
You mean this:

<img width="780" alt="screen shot 2016-02-09 at 00 02 45" src="https://cloud.githubusercontent.com/assets/439593/12902273/78ccb3ea-cec0-11e5-8355-448e55947c93.png">

It works fine for me... maybe could you try re-downloading from the releases section. Then first try quitting System Preferences completely before installing. Finally, you could try removing the PostgreSQL preferences first (right-click on the icon, select Remove) and then install again.

Let me know if you still don't see the starting/stopping image.

**Comment by pedrocatalao** [comment]
Ah perfect, just had to quit and open system preferences again, looks good :)

**Comment by mckenfra** [comment]
Great, glad it works. Thanks again for raising the fish issue, and for the cool icons :)
